# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cnp', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_at')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update_at')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.Facultate')),
            ],
        ),
    ]
