# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
        ('ProfessorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucrare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titluLucrare', models.CharField(blank=True, max_length=254)),
                ('tipLucrare', models.CharField(blank=True, choices=[('L', 'Licenta'), ('D', 'Disertatie')], max_length=1)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_at')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update_at')),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfessorApp.Professor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.Student')),
            ],
        ),
    ]
