# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cnp',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
