# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 18:30
from __future__ import unicode_literals

import ProfessorApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[ProfessorApp.validators.validate_file_extension]),
        ),
    ]
