# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorApp', '0002_lucrare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lucrare',
            name='profesor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ProfessorApp.Professor'),
        ),
    ]
