# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorApp', '0003_auto_20180624_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.Facultate'),
        ),
    ]
