# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorApp', '0004_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='descriere',
        ),
    ]
