# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_auto_20180601_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.Facultate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specializations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.Specializare'),
        ),
    ]
